# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-29 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaigns')),
            ],
            options={
                'ordering': ['campaign', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=255, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Fields')),
            ],
            options={
                'ordering': ['includes', 'field'],
            },
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('G', 'G'), ('V', 'V')], max_length=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['register'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, default='', max_length=25)),
                ('regnum', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Blocks')),
            ],
            options={
                'ordering': ['regnum'],
            },
        ),
        migrations.AddField(
            model_name='edit',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Register'),
        ),
        migrations.AddField(
            model_name='edit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data',
            name='includes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Register'),
        ),
    ]
