# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-29 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('imagePath', models.CharField(max_length=125)),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customers')),
                ('idworker', models.ManyToManyField(to='main.DataEntryUser')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('int', 'int'), ('dec', 'dec'), ('str', 'str'), ('bool', 'bool')], max_length=6)),
                ('length', models.SmallIntegerField()),
                ('fieldNum', models.SmallIntegerField()),
                ('screenNumber', models.SmallIntegerField()),
                ('imgPos', models.CommaSeparatedIntegerField(max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaigns')),
            ],
            options={
                'ordering': ['fieldNum'],
            },
        ),
        migrations.CreateModel(
            name='fieldsPerformsProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(max_length=50)),
                ('value2', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Fields')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=35)),
                ('value', models.CharField(max_length=255)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.List')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='PropertiesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.CharField(max_length=255)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='campaigns.Properties')),
            ],
            options={
                'managed': True,
                'db_table': 'campaigns_properties_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'properties Translation',
            },
        ),
        migrations.AddField(
            model_name='fieldsperformsproperties',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Properties'),
        ),
        migrations.AlterUniqueTogether(
            name='propertiestranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
