# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-29 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=220)),
                ('telephone', models.CharField(max_length=19)),
                ('email', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('GV', 'Worker'), ('MN', 'Data Entry Monitor'), ('PG', 'Developer')], max_length=2)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French')], default='en-us', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
